In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Elite' 12.0 10000.0]
 ['Master' 12.0 30000.0]
 ['Grandmaster' 16.0 65000.0]
 ['Epic' 25.0 150000.0]
 ['Legend' 25.0 nan]
 ['Mythic' nan 20000.0]]


In [ ]:
print(y)

['Yes' 'Yes' 'Yes' 'Yes' 'No' 'No']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['Elite' 12.0 10000.0]
 ['Master' 12.0 30000.0]
 ['Grandmaster' 16.0 65000.0]
 ['Epic' 25.0 150000.0]
 ['Legend' 25.0 55000.0]
 ['Mythic' 18.0 20000.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 12.0 10000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 12.0 30000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 16.0 65000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 25.0 150000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 25.0 55000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 18.0 20000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 1 1 1 0 0]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test, = train_test_split(x, y, test_size=0.2, random_state = 1)

In [ ]:
print(x_train)

[[0.0 0.0 0.0 1.0 0.0 0.0 25.0 55000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 12.0 10000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 25.0 150000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 18.0 20000.0]]


In [ ]:
print(x_test)

[[0.0 0.0 1.0 0.0 0.0 0.0 16.0 65000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 12.0 30000.0]]


In [ ]:
print(y_train)

[0 1 1 0]


In [ ]:
print(y_test)

[1 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 0.0 0.0 1.7320508075688774 0.0 -0.5773502691896258
  0.9205746178983234 -0.06784969095478509]
 [1.0 0.0 0.0 -0.5773502691896258 0.0 -0.5773502691896258
  -1.4729193886373175 -0.8820459824122062]
 [0.0 1.0 0.0 -0.5773502691896258 0.0 -0.5773502691896258
  0.9205746178983234 1.6510091465664374]
 [0.0 0.0 0.0 -0.5773502691896258 0.0 1.7320508075688774
  -0.3682298471593294 -0.701113473199446]]


In [ ]:
print(x_test)

[[0.0 0.0 1.0 -0.5773502691896258 0.0 -0.5773502691896258
  -0.7364596943186588 0.11308281825797516]
 [0.0 0.0 0.0 -0.5773502691896258 1.0 -0.5773502691896258
  -1.4729193886373175 -0.5201809639866857]]
